name: Experiment
on: 
  schedule:
  - cron: '*/1 * * * *'

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: cURL request
    # Hit the webhook endpoint to rebuild  from the "main" branch
      run: curl -i https://covidrescue.co.in/api/check-send-notification
